### ISSUE TITLE
lab1

### ISSUE THREAD

**Issue by lzl-hello** [ErnestThePoet/CompilationPrinciples#1]
学长，请问lab1的测试extra6.cmm的输出正确吗？
![image](https://github.com/ErnestThePoet/CompilationPrinciples/assets/96810799/791050f3-31a5-4faf-9859-9f9547e2029a)
只识别到了第三行的错误，第四行那个没有识别出来

**Comment by ErnestThePoet** [comment]
印象中确实有这个问题，但是去年验收的时候没有扣分
